[project]
name = "log-auditor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hajuanas92-code", email = "hajuanas92@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-cloud-logging>=3.16.3",
    "python-dotenv>=1.2.3",
]